---
- name: update apt
  apt: update_cache=yes upgrade=safe
- name: update sources apt
  copy: src=sources.list dest=/etc/apt/sources.list
- name: Create deny-ssh-group
  group: name=deny-ssh system=yes state=present
- name: update sshd server
  copy: src=sshd_config dest=/etc/ssh/sshd_config
  notify: restart sshd
- name: update sudoers
  template: src=sudoers.txt dest=/etc/sudoers validate='visudo -cf %s'
- name: install ufw
  apt: name=ufw state=present
- name: Reset the firewall (purges any additional rules)
  ufw: state=reset
- name: Insert ufw rules
  ufw: rule={{item.rule}} proto={{item.proto}} port={{item.port}}
  with_items: "{{ufw.basic_ports}}"
- name: Enable policy
  ufw: policy={{ufw.default_policy}} state=enabled logging=on